hearsay_content_configurations.settings_form:
  title: 'Hearsay Content Configurations'
  route_name: hearsay_content_configurations.settings_form
  description: 'Hearsay Content Configurations'
  parent: system.admin_config
  weight: -15

hearsay_content_configurations.library_team_settings_form:
  title: 'Library Team Content Configurations'
  route_name: hearsay_content_configurations.library_team_settings_form
  description: 'Library Team Content Configurations'
  parent: system.admin_config
  weight: -15

hearsay_content_configurations.library_individual_settings_form:
  title: 'Library Individual Content Configurations'
  route_name: hearsay_content_configurations.library_individual_settings_form
  description: 'Library Individual Content Configurations'
  parent: system.admin_config
  weight: -15

hearsay_content_configurations.npg_settings_form:
  title: 'NPG Content Configurations'
  route_name: hearsay_content_configurations.npg_settings_form
  description: 'NPG Content Configurations'
  parent: system.admin_config
  weight: -15

hearsay_content_configurations.p3_settings_form:
  title: 'P3 Content Configurations'
  route_name: hearsay_content_configurations.p3_settings_form
  description: 'P3 Content Configurations'
  parent: system.admin_config
  weight: -15