name: 'Hearsay Content Configurations'
description: 'Admin configuration for Hearsay where they can change title/text and images for each component'
type: module
core_version_requirement: '^9 || ^10'
package: Hearsay